def arabic_to_roman(number: float) -> str: ...


def roman_to_arabic(numeral: str) -> int | float: ...


def arabic_to_greek(number: float, positional: bool, capital: bool) -> str: ...


def greek_to_arabic(numeral: str, positional: bool, capital: bool) -> int | float: ...
