def arabic_to_roman(number: int) -> str: ...


def roman_to_arabic(numeral: str) -> int: ...


def arabic_to_greek(number: int, positional: bool, capital: bool) -> str: ...


def greek_to_arabic(numeral: str, positional: bool, capital: bool) -> int: ...
